# Generated by Django 4.2.4 on 2023-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_company_event_jobprofile_placement_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='job_profile',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(null=True, upload_to='profile_pic/'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='JobProfile',
        ),
        migrations.DeleteModel(
            name='Placement',
        ),
    ]
